# Generated by Django 4.2.1 on 2023-05-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sensor', models.CharField(max_length=30, verbose_name='Наименование датчика')),
                ('description', models.CharField(max_length=50, verbose_name='Расположение датчика')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура измерения')),
                ('data_measur', models.DateTimeField(auto_now_add=True, verbose_name='Дата измерения')),
                ('id_sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measurement.sensor', verbose_name='ID Датчика')),
            ],
        ),
    ]
